server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-customer
  zipkin:
    baseUrl: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  data:
    mongodb:
      username: usr-customer-mongo
      password: pwd-customer-mongo
      database: customer-dev-mongo
      port: 27017
      host: localhost

info:
  application:
    name: api-customer

eureka:
   healthcheck:
     enabled: true
   instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/



resilience4j:
  retry:
    configs:
      default:
        max-retry-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
      instances:
        retryCustomer:
          base-config: default
          max-retry-attempts: 5
          wait-duration: 2s
          retry-exceptions:
            - java.net.ConnectException
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
    instances:
      createCustomer:
        base-config: default
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        wait-duration-in-open-state: 1m
        failure-rate-threshold: 20

